### ISSUE TITLE
IIgs mouse driver puts the system back in emulation mode

### ISSUE THREAD

**Issue by dwsJason** [blondie7575/WeeGUI#21]
The new IIgs mouse driver puts the system back in emulation mode.   This isn't very friendly when WeeGUI is being used for a GS native app.

I suggest preserving the status register, and restoring it instead.   This does make the driver 1 byte larger.   Updated file attached.

[mouse_gs.zip](https://github.com/blondie7575/WeeGUI/files/1822138/mouse_gs.zip)

**Comment by blondie7575** [comment]
Pull requests always welcome!
