### ISSUE TITLE
It would be nice to support a white background

### ISSUE THREAD

**Issue by sicklittlemonkey** [blondie7575/WeeGUI#4]
Hi guys.

Just a quick note - it looks like MouseText was designed to mimic the Mac, and have a white background. You can see how this would fix several display quirks that Quinn complained about at Kfest. Anyway, great work! : - )

Exhibit A!
https://archive.org/details/Developers_Handbook_for_the_Apple_II_MouseText_Tool_Kit
(Don't worry, only the cover is French!)

Cheers,
Nick.

**Comment by blondie7575** [comment]
The color can't be controlled, and there aren't inverse MouseText characters in the ROM. The look it has is the only option. :)

**Comment by sicklittlemonkey** [comment]
Well, I was thinking just the window text contents, which can be white on black. But yeah, I suppose if you have MouseText on controls in the Window - which I now see is the case in the style guide in the doc I linked to - some of those controls can't be black on white.

Ticks for radio buttons and checkboxes would be ok, but Apple has flipped on the style in the guide and gone with white on black for the rest.

Still, if you haven't seen it you might want to look at the window "chrome" (title and scroll bars) on the original event driven Mouse Took Kit. Antoine pointed me to the disks:
http://www.brutaldeluxe.fr/documentation/forumdesdeveloppeurs.html

I'll paste an image below.

Cheers,
Nick.

![mousetexttookkitdemo](https://cloud.githubusercontent.com/assets/4393005/9006941/b7b209f6-37e0-11e5-8fa0-d0923eec48b3.png)
